mesh:
  enabled: true
  image_version: 1.13.1-2
  public_port: 4666 # the port where TLS will be exposed
  # Enable telemetry
  telemetry:
    enabled: true
    port: 9361

ingress:
  enabled: true
  base_cors_policy: true
