apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "base.meta.metadata" (dict "Root" .) | indent 2 }}
spec:
  selector:
  {{- include "base.meta.selector" . | indent 4 }}
  replicas: {{ .Values.resources.replicas }}
  template:
    metadata:
      labels:
        {{- include "base.meta.pod_labels" . | indent 8 }}
      annotations:
        {{- include "base.meta.pod_annotations" . | indent 8 }}
        {{- include "mesh.name.annotations" . | indent 8 }}
    spec:
      {{- if .Values.affinity }}
      {{- toYaml .Values.affinity | nindent 6 }}
      {{- end }}
      containers:
        {{- include "lamp.httpd.container" . | indent 8 }}
        ## Add any additional volumes for apache configuration here.
        ## Indentation level: 10
        {{- include "lamp.phpfpm.container" . | indent 8 }}
        {{- if .Values.monitoring.enabled }}
        {{- include "lamp.httpd.exporter" . | indent 8 }}
        {{- include "lamp.phpfpm.exporter" . | indent 8 }}
        {{- end }}
        {{- include "mesh.deployment.container" . | indent 8 }}
        {{- include "base.statsd.container" . | indent 8 }}
        {{- include "cache.mcrouter.container" . | indent 8 }}
      volumes:
        # httpd custom configuration.
        {{- include "lamp.httpd.volume" . | indent 8 }}
        # Shared unix socket
        {{- include "lamp.common.socket" . | indent 8 }}
        # Application configuration, in /srv/app/config.json
        {{- include "lamp.phpfpm.volume" . | indent 8 }}
        {{- include "mesh.deployment.volume" . | indent 8 }}
        {{- include "base.statsd.volume" . | indent 8 }}
        {{- include "cache.mcrouter.volume" . | indent 8 }}



