mesh:
  enabled: true
  image_version: 1.13.1-2
  public_port: 4666 # the port where TLS will be exposed
  # Enable telemetry
  telemetry:
    enabled: true
    port: 9361

ingress:
  enabled: true
  existingGatewayName: "some/gateway"
  routeHosts:
    - somehost.somedomain.sometld
    - chart.discovery.wmnet
  httproutes:
    - match:
        - uri:
            prefix: /blaaa
    - match:
        - uri:
            prefix: /dsjsldfblaaa
      route:
        - destination:
            host: blablabla
            port:
              number: 555
